repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.10
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    # Keep version in sync with your uv package version
    rev: 0.6.9
    hooks:
      - id: uv-lock # Locks the uv lockfile
  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.30.0"
    hooks:
    -   id: django-upgrade
        args: [--target-version, "6.0"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
    -   id: pyupgrade
