repos:
  - repo: https://github.com/pycqa/isort
    rev: 8.0.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
  - repo: https://github.com/astral-sh/uv-pre-commit
    # Keep version in sync with your uv package version
    rev: 0.6.9
    hooks:
      - id: uv-lock # Locks the uv lockfile
  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.30.0"
    hooks:
    -   id: django-upgrade
        args: [--target-version, "6.0"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
    -   id: pyupgrade
